volumes:
  instarchiver_production_postgres_data: {}
  instarchiver_production_postgres_data_backups: {}
  instarchiver_production_traefik: {}
  instarchiver_production_django_media: {}
  instarchiver_production_redis_data: {}


services:
  django: &django
    image: ghcr.io/instarchiver/instarchiver-backend/django:latest
    volumes:
      - instarchiver_production_django_media:/app/core/media
    depends_on:
      - pgbouncer
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    image: ghcr.io/instarchiver/instarchiver-backend/postgres:latest
    ports:
      - 100.73.60.108:65432:5432
    volumes:
      - instarchiver_production_postgres_data:/var/lib/postgresql/data
      - instarchiver_production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:6
    volumes:
      - instarchiver_production_redis_data:/data
    ports:
      - 100.73.60.108:64202:6379

  pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=200
      - DEFAULT_POOL_SIZE=25
      - MIN_POOL_SIZE=5
      - RESERVE_POOL_SIZE=5
      - SERVER_RESET_QUERY=DISCARD ALL
    env_file:
      - ./.envs/.production/.postgres
    depends_on:
      - postgres
    restart: unless-stopped

  celeryworker:
    <<: *django
    image: ghcr.io/instarchiver/instarchiver-backend/django:latest
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ghcr.io/instarchiver/instarchiver-backend/django:latest
    command: /start-celerybeat

  flower:
    <<: *django
    image: ghcr.io/instarchiver/instarchiver-backend/django:latest
    command: /start-flower

  nginx:
    image: ghcr.io/instarchiver/instarchiver-backend/nginx:latest
    depends_on:
      - django
    volumes:
      - instarchiver_production_django_media:/usr/share/nginx/media:ro
    ports:
      - 100.73.60.108:64001:80

  awscli:
    image: ghcr.io/instarchiver/instarchiver-backend/awscli:latest
    env_file:
      - ./.envs/.production/.django
    volumes:
      - instarchiver_production_postgres_data_backups:/backups:z
