volumes:
  instarchiver_local_postgres_data: {}
  instarchiver_local_postgres_data_backups: {}
  instarchiver_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: instarchiver_local_django
    container_name: instarchiver_local_django
    depends_on:
      - pgbouncer
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: instarchiver_production_postgres
    container_name: instarchiver_local_postgres
    volumes:
      - instarchiver_local_postgres_data:/var/lib/postgresql/data
      - instarchiver_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '54321:5432'

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: instarchiver_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: instarchiver_local_redis
    volumes:
      - instarchiver_local_redis_data:/data

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: instarchiver_local_pgbouncer
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=200
      - DEFAULT_POOL_SIZE=25
      - MIN_POOL_SIZE=5
      - RESERVE_POOL_SIZE=5
      - SERVER_RESET_QUERY=DISCARD ALL
    env_file:
      - ./.envs/.local/.postgres
    depends_on:
      - postgres

  celeryworker:
    <<: *django
    image: instarchiver_local_celeryworker
    container_name: instarchiver_local_celeryworker
    depends_on:
      - redis
      - pgbouncer
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: instarchiver_local_celerybeat
    container_name: instarchiver_local_celerybeat
    depends_on:
      - redis
      - pgbouncer
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: instarchiver_local_flower
    container_name: instarchiver_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
